# Generated by Django 4.2.4 on 2023-09-06 18:41

import aplic.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):
    dependencies = [
        ("aplic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "foto",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=aplic.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Foto",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Twitter"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Instagram"
                    ),
                ),
                (
                    "matricula",
                    models.IntegerField(unique=True, verbose_name="Matrícula"),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True,
                        help_text="Formato DD/MM/AAAA",
                        null=True,
                        verbose_name="Data de Nascimento",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=200, verbose_name="E-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
            },
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("carga_horaria", models.IntegerField(verbose_name="Carga horária")),
                (
                    "obrigatoria",
                    models.BooleanField(default=True, verbose_name="Obrigatória"),
                ),
                (
                    "ementa",
                    models.TextField(blank=True, max_length=500, verbose_name="Ementa"),
                ),
                (
                    "bibliografia",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Bibliografia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "foto",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=aplic.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Foto",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Twitter"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Instagram"
                    ),
                ),
                (
                    "titulacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Doutorado", "Doutorado"),
                            ("Mestrado", "Mestrado"),
                            ("Especialização", "Especialização"),
                            ("Graduação", "Graduação"),
                        ],
                        max_length=100,
                        verbose_name="Titulação",
                    ),
                ),
                (
                    "curriculo",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Currículo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to=aplic.models.get_file_path,
                variations={"thumb": {"crop": True, "height": 260, "width": 420}},
                verbose_name="Imagem",
            ),
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(verbose_name="Ano")),
                ("semestre", models.IntegerField(verbose_name="Semestre")),
                ("turma", models.CharField(max_length=10, verbose_name="Turma")),
                ("alunos", models.ManyToManyField(to="aplic.aluno")),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplic.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aplic.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
            },
        ),
        migrations.AddField(
            model_name="professor",
            name="curso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aplic.curso",
            ),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinas",
                to="aplic.curso",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="aplic.curso"
            ),
        ),
    ]
